# Generated by Django 4.0 on 2022-03-06 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ManagerName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerName', models.CharField(max_length=50)),
                ('CustomerPostalCode', models.IntegerField(max_length=5)),
                ('CustomerAddress', models.CharField(max_length=250)),
                ('CustomerManager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finder.salesmanager')),
            ],
        ),
    ]
