# Generated by Django 4.0 on 2022-03-06 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Finder', '0002_alter_customer_customerpostalcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostalCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('City', models.CharField(max_length=20)),
                ('District', models.CharField(max_length=20)),
                ('Region', models.CharField(max_length=20)),
                ('Code', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='CustomerPostalCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finder.postalcode'),
        ),
    ]
