# Generated by Django 4.0 on 2022-03-08 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Finder', '0003_postalcode_alter_customer_customerpostalcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='CustomerAddress',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='CustomerManager',
            new_name='manager',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='CustomerName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='CustomerPostalCode',
            new_name='postal_code',
        ),
        migrations.RenameField(
            model_name='postalcode',
            old_name='City',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='postalcode',
            old_name='Code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='postalcode',
            old_name='District',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='postalcode',
            old_name='Region',
            new_name='region',
        ),
        migrations.RenameField(
            model_name='salesmanager',
            old_name='ManagerName',
            new_name='manager_name',
        ),
    ]
